name: arc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  get: ^4.6.5
  bot_toast: ^4.0.2
  fluttertoast: ^8.0.9
  flutter_bluetooth_serial:
    path: plugins/flutter_bluetooth_serial-android-12-fixes
  cupertino_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  scoped_model: ^1.1.0
  fl_chart: ^0.51.0
  path_provider: ^2.0.11
  intl: ^0.17.0
  direct_select: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3
  #flutter pub run flutter_launcher_icons:main -f pubspec.yaml
  flutter_native_splash: ^2.2.3
  #flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ios-icon.png"
  image_path_android: "assets/launcher/android-icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


flutter_native_splash:
  color: "#000000"
  image: assets/splash/splash.png